### ISSUE TITLE
It should not have any impact if a users adds a bill which is paid by him and only belongs to himself.

### ISSUE THREAD

**Issue by duffleit** [nobt-io/frontend#10]
![2017-05-23_01-33-43](https://cloud.githubusercontent.com/assets/7366006/26332717/d9456a3c-3f58-11e7-96dc-f3f18a694c82.gif)

Only happens, if nobt does not contain any bill yet.

**Comment by thomaseizinger** [comment]
This seems to be a backend and not a frontend bug and should therefore be fixed in the backend.
