### ISSUE TITLE
Make source-maps public?

### ISSUE THREAD

**Issue by thomaseizinger** [nobt-io/frontend#46]
What do you guys think?
Should we also upload the source-maps for our minified JS-code to AWS?
- The code of our project is open-source anyway (so protecting it by not making the source-maps public does not make much sense)
- We would not have to upload the source-maps to sentry in order to ease debugging (this means, one script less to execute during our deployment)

**Comment by KreMat** [comment]
I agree - in an open source project I don't see any reason to hide it

**Comment by thomaseizinger** [comment]
There is one thing that I did not think about before.
By uploading the source-maps + source to Sentry, we persist the actual "binaries" that were running in production. We cannot get around uploading them because otherwise Sentry would have to re-fetch the source + source-maps everytime you want to view an error. If a new release happens in-between, the old source-maps would be lost.

So making the source-maps public does not provide any benefit. I will close this as no longer relevant then.
